services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d db"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data
      - type: bind
        source: /home/administrador/Docker/postgres/postgres_custom
        target: /etc/postgresql
    entrypoint: docker-entrypoint.sh -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      - net
volumes:
  pg_data:
    driver: local

networks:
  net:
    driver: overlay