services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db
      - UTC=-3
      - TIMEZONE=America/Sao_Paulo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d db"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres_custom:/etc/postgresql
    networks:
      - net
volumes:
  pg_data:
    driver: local

networks:
  net:
    driver: bridge